#!/bin/bash

# Check if user 'hema' exists
if id "hema" &>/dev/null; then
    echo "User 'hema' already exists"
else
    sudo adduser hema
    echo "Added user 'hema'"
fi

# Check if group 'hamza' exists
if getent group "hamza" &>/dev/null; then
    echo "Group 'hamza' already exists"
else
    sudo groupadd hamza
    echo "Added Group 'hamza'"
fi

# Add user 'hema' to group 'hamza'
sudo usermod -aG hamza hema

# Display information about user 'hema' and group 'hamza'
id hema
getent group hamza

